### ISSUE TITLE
MTabix caching key collision

### ISSUE THREAD

**Issue by mpschr** [gitools/gitools#156]
Here below a problem that cause the values that are displayed in the matrix are being changed for one gene GAS5 to the values of the otrhe gene GAS5. This should be the same issue as #155.

Here below I print always the identifier pair followed by the long-value used as a key in the class [MTabixMatrix at line 143](https://github.com/gitools/gitools/blob/61edd3ca33219e46b7c4d4bec70228d8c18ba7cc/org.gitools.matrix/src/main/java/org/gitools/matrix/model/mtabixmatrix/MTabixMatrix.java#L143):

    PL08_REL	GAS5
    9364113182542526
    PL08_REL	GART
    9364113182542526
    PE05_REL	GAS5
    9364111262213492
    PE05_REL	GART
    9364111262213492
    PE04_REL	GAS5
    9364111261289971
    PE04_REL	GART
    9364111261289971
    PE04_ID	GAS5
    9364111044272225
    PE04_ID	GART
    9364111044272225
    PE07_ID	GAS5
    9364111044361598
    PE07_ID	GART
    9364111044361598
    PL07_ID	GAS5
    9364111244765655
    PL07_ID	GART
    9364111244765655

**Comment by mpschr** [comment]
In fact, could we be using a common HashMap at the above linked code junk, @jordeu ?

**Comment by jordeu** [comment]
I'm writing a unit test to reproduce this bug. We are using TLongDoubleMap instead of HashMap because it is more memory efficient and if we use mtabix is because we need to reduce the memory footprint. I'm still not sure, but I think that the problem is in the "parseHash" function not in the matrix hash it self. I'll commit the unit test when it's ready.

**Comment by mpschr** [comment]
Ok, I see.

If you like you can use the gene symbol list as ids for the unit test (53k of symbols)
[genesymbols.txt](https://github.com/gitools/gitools/files/111912/genesymbols.txt)
