### ISSUE TITLE
Modules download error: Error parsing Biomart query results

### ISSUE THREAD

**Issue by mpschr** [gitools/gitools#157]
Reported by Khademul, confirmed by me.
![errorgitools](https://cloud.githubusercontent.com/assets/1090105/12881829/3079529c-ce4d-11e5-9d45-0e484c92915a.png)

**Comment by mpschr** [comment]
Apparently the connection is being reset because there is no response. 

An example query sent by Gitools is: 

http://www.ensembl.org:80/biomart/martservice?query=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%3C%21DOCTYPE+Query%3E%3CQuery+virtualSchemaName%3D%22default%22+header%3D%220%22+uniqueRows%3D%221%22+count%3D%220%22+formatter%3D%22TSV%22+datasetConfigVersion%3D%220.7%22%3E%3CDataset+name%3D%22hsapiens_gene_ensembl%22+interface%3D%22default%22%3E%3CAttribute+name%3D%22go_id%22+%2F%3E%3CAttribute+name%3D%22name_1006%22+%2F%3E%3CAttribute+name%3D%22namespace_1003%22+%2F%3E%3C%2FDataset%3E%3C%2FQuery%3E

**Comment by jordeu** [comment]
This seems a problem at the ensembl biomart server that sometimes is not working or the download rate is very slow.
